name: GitHub script test

on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    # language=bash
    - run: |
        echo $JAVA_HOME_17_X64
        set JAVA_HOME=$(echo $JAVA_HOME_17_X64)
        echo $JAVA_HOME
